-- ////////////////////////////////////
-- ////////// engine //////////////////
-- ////////////////////////////////////

CREATE TABLESPACE LKMCTS01
IN LKMCDB03
  USING STOGROUP DB0DSG05
PRIQTY -1 SECQTY -1
BUFFERPOOL BP9;

CREATE TABLE LKMC.ACT_GE_PROPERTY (
  NAME_  VARCHAR(64) NOT NULL,
  VALUE_ VARCHAR(300),
  REV_   INTEGER,
  PRIMARY KEY (NAME_)
)
IN LKMCDB03.LKMCTS01;

CREATE UNIQUE INDEX LKMC.ACT_GE_PROPERTY_NAME
  ON LKMC.ACT_GE_PROPERTY (NAME_);

INSERT INTO LKMC.ACT_GE_PROPERTY
VALUES ('schema.version', '5.21.0.0', 1);

INSERT INTO LKMC.ACT_GE_PROPERTY
VALUES ('schema.history', 'create(5.21.0.0)', 1);

INSERT INTO LKMC.ACT_GE_PROPERTY
VALUES ('next.dbid', '1', 1);

---------------------------------

CREATE TABLESPACE LKMCTS02
IN LKMCDB03
  USING STOGROUP DB0DSG05
PRIQTY -1 SECQTY -1
BUFFERPOOL BP9;

CREATE TABLE LKMC.ACT_GE_BYTEARRAY (
  ID_            VARCHAR(64) NOT NULL,
  REV_           INTEGER,
  NAME_          VARCHAR(255),
  DEPLOYMENT_ID_ VARCHAR(64),
  BYTES_         BLOB,
  GENERATED_     SMALLINT CHECK (GENERATED_ IN (1, 0)),
  PRIMARY KEY (ID_)
)
IN LKMCDB03.LKMCTS02;

CREATE UNIQUE INDEX LKMC.ACT_GE_BYTEARRAY_ID
  ON LKMC.ACT_GE_BYTEARRAY (ID_);

---------------------------------

CREATE TABLESPACE LKMCTS03
IN LKMCDB03
  USING STOGROUP DB0DSG05
PRIQTY -1 SECQTY -1
BUFFERPOOL BP9;

CREATE TABLE LKMC.ACT_RE_DEPLOYMENT (
  ID_          VARCHAR(64) NOT NULL,
  NAME_        VARCHAR(255),
  CATEGORY_    VARCHAR(255),
  TENANT_ID_   VARCHAR(255) DEFAULT '',
  DEPLOY_TIME_ TIMESTAMP,
  PRIMARY KEY (ID_)
)
IN LKMCDB03.LKMCTS03;

CREATE UNIQUE INDEX LKMC.ACT_RE_DEPLOYMENT_ID
  ON LKMC.ACT_RE_DEPLOYMENT (ID_);

---------------------------------

CREATE TABLESPACE LKMCTS04
IN LKMCDB03
  USING STOGROUP DB0DSG05
PRIQTY -1 SECQTY -1
BUFFERPOOL BP8K1;

CREATE TABLE LKMC.ACT_RE_MODEL (
  ID_                           VARCHAR(64) NOT NULL,
  REV_                          INTEGER,
  NAME_                         VARCHAR(255),
  KEY_                          VARCHAR(255),
  CATEGORY_                     VARCHAR(255),
  CREATE_TIME_                  TIMESTAMP,
  LAST_UPDATE_TIME_             TIMESTAMP,
  VERSION_                      INTEGER,
  META_INFO_                    VARCHAR(4000),
  DEPLOYMENT_ID_                VARCHAR(64),
  EDITOR_SOURCE_VALUE_ID_       VARCHAR(64),
  EDITOR_SOURCE_EXTRA_VALUE_ID_ VARCHAR(64),
  TENANT_ID_                    VARCHAR(255) DEFAULT '',
  PRIMARY KEY (ID_)
)
IN LKMCDB03.LKMCTS04;

CREATE UNIQUE INDEX LKMC.ACT_RE_MODEL_ID
  ON LKMC.ACT_RE_MODEL (ID_);

---------------------------------

CREATE TABLESPACE LKMCTS05
IN LKMCDB03
  USING STOGROUP DB0DSG05
PRIQTY -1 SECQTY -1
BUFFERPOOL BP9;

CREATE TABLE LKMC.ACT_RU_EXECUTION (
  ID_               VARCHAR(64) NOT NULL,
  REV_              INTEGER,
  PROC_INST_ID_     VARCHAR(64),
  BUSINESS_KEY_     VARCHAR(255),
  PARENT_ID_        VARCHAR(64),
  PROC_DEF_ID_      VARCHAR(64),
  SUPER_EXEC_       VARCHAR(64),
  ACT_ID_           VARCHAR(255),
  IS_ACTIVE_        SMALLINT CHECK (IS_ACTIVE_ IN (1, 0)),
  IS_CONCURRENT_    SMALLINT CHECK (IS_CONCURRENT_ IN (1, 0)),
  IS_SCOPE_         SMALLINT CHECK (IS_SCOPE_ IN (1, 0)),
  IS_EVENT_SCOPE_   SMALLINT CHECK (IS_EVENT_SCOPE_ IN (1, 0)),
  SUSPENSION_STATE_ INTEGER,
  CACHED_ENT_STATE_ INTEGER,
  TENANT_ID_        VARCHAR(255) DEFAULT '',
  NAME_             VARCHAR(255),
  LOCK_TIME_        TIMESTAMP,
  PRIMARY KEY (ID_)
) IN LKMCDB03.LKMCTS05;

CREATE UNIQUE INDEX LKMC.ACT_RU_EXECUTION_ID
  ON LKMC.ACT_RU_EXECUTION (ID_);

---------------------------------

CREATE TABLESPACE LKMCTS06
IN LKMCDB03
  USING STOGROUP DB0DSG05
PRIQTY -1 SECQTY -1
BUFFERPOOL BP32K2;

CREATE TABLE LKMC.ACT_RU_JOB (
  ID_                  VARCHAR(64)  NOT NULL,
  REV_                 INTEGER,
  TYPE_                VARCHAR(255) NOT NULL,
  LOCK_EXP_TIME_       TIMESTAMP,
  LOCK_OWNER_          VARCHAR(255),
  EXCLUSIVE_           SMALLINT CHECK (EXCLUSIVE_ IN (1, 0)),
  EXECUTION_ID_        VARCHAR(64),
  PROCESS_INSTANCE_ID_ VARCHAR(64),
  PROC_DEF_ID_         VARCHAR(64),
  RETRIES_             INTEGER,
  EXCEPTION_STACK_ID_  VARCHAR(64),
  EXCEPTION_MSG_       VARCHAR(4000),
  DUEDATE_             TIMESTAMP,
  REPEAT_              VARCHAR(255),
  HANDLER_TYPE_        VARCHAR(255),
  HANDLER_CFG_         VARCHAR(4000),
  TENANT_ID_           VARCHAR(255) DEFAULT '',
  PRIMARY KEY (ID_)
) IN LKMCDB03.LKMCTS06;

CREATE UNIQUE INDEX LKMC.ACT_RU_JOB_ID
  ON LKMC.ACT_RU_JOB (ID_);

---------------------------------

CREATE TABLESPACE LKMCTS07
IN LKMCDB03
  USING STOGROUP DB0DSG05
PRIQTY -1 SECQTY -1
BUFFERPOOL BP32K2;

CREATE TABLE LKMC.ACT_RE_PROCDEF (
  ID_                     VARCHAR(64)  NOT NULL,
  REV_                    INTEGER,
  CATEGORY_               VARCHAR(255),
  NAME_                   VARCHAR(255),
  KEY_                    VARCHAR(255) NOT NULL,
  VERSION_                INTEGER      NOT NULL,
  DEPLOYMENT_ID_          VARCHAR(64),
  RESOURCE_NAME_          VARCHAR(4000),
  DGRM_RESOURCE_NAME_     VARCHAR(4000),
  DESCRIPTION_            VARCHAR(4000),
  HAS_START_FORM_KEY_     SMALLINT CHECK (HAS_START_FORM_KEY_ IN (1, 0)),
  HAS_GRAPHICAL_NOTATION_ SMALLINT CHECK (HAS_GRAPHICAL_NOTATION_ IN (1, 0)),
  SUSPENSION_STATE_       INTEGER,
  TENANT_ID_              VARCHAR(255) NOT NULL DEFAULT '',
  PRIMARY KEY (ID_)
) IN LKMCDB03.LKMCTS07;

CREATE UNIQUE INDEX LKMC.ACT_RE_PROCDEF_ID
  ON LKMC.ACT_RE_PROCDEF (ID_);

---------------------------------

CREATE TABLESPACE LKMCTS08
IN LKMCDB03
  USING STOGROUP DB0DSG05
PRIQTY -1 SECQTY -1
BUFFERPOOL BP8K1;

CREATE TABLE LKMC.ACT_RU_TASK (
  ID_               VARCHAR(64) NOT NULL,
  REV_              INTEGER,
  EXECUTION_ID_     VARCHAR(64),
  PROC_INST_ID_     VARCHAR(64),
  PROC_DEF_ID_      VARCHAR(64),
  NAME_             VARCHAR(255),
  PARENT_TASK_ID_   VARCHAR(64),
  DESCRIPTION_      VARCHAR(4000),
  TASK_DEF_KEY_     VARCHAR(255),
  OWNER_            VARCHAR(255),
  ASSIGNEE_         VARCHAR(255),
  DELEGATION_       VARCHAR(64),
  PRIORITY_         INTEGER,
  CREATE_TIME_      TIMESTAMP,
  DUE_DATE_         TIMESTAMP,
  CATEGORY_         VARCHAR(255),
  SUSPENSION_STATE_ INTEGER,
  TENANT_ID_        VARCHAR(255) DEFAULT '',
  FORM_KEY_         VARCHAR(255),
  PRIMARY KEY (ID_)
) IN LKMCDB03.LKMCTS08;

CREATE UNIQUE INDEX LKMC.ACT_RU_TASK_ID
  ON LKMC.ACT_RU_TASK (ID_);

---------------------------------

CREATE TABLESPACE LKMCTS09
IN LKMCDB03
  USING STOGROUP DB0DSG05
PRIQTY -1 SECQTY -1
BUFFERPOOL BP9;

CREATE TABLE LKMC.ACT_RU_IDENTITYLINK (
  ID_           VARCHAR(64) NOT NULL,
  REV_          INTEGER,
  GROUP_ID_     VARCHAR(255),
  TYPE_         VARCHAR(255),
  USER_ID_      VARCHAR(255),
  TASK_ID_      VARCHAR(64),
  PROC_INST_ID_ VARCHAR(64),
  PROC_DEF_ID_  VARCHAR(64),
  PRIMARY KEY (ID_)
) IN LKMCDB03.LKMCTS09;

CREATE UNIQUE INDEX LKMC.ACT_RU_IDENTITYLINK_ID
  ON LKMC.ACT_RU_IDENTITYLINK (ID_);

---------------------------------

CREATE TABLESPACE LKMCTS10
IN LKMCDB03
  USING STOGROUP DB0DSG05
PRIQTY -1 SECQTY -1
BUFFERPOOL BP32K2;

CREATE TABLE LKMC.ACT_RU_VARIABLE (
  ID_           VARCHAR(64)  NOT NULL,
  REV_          INTEGER,
  TYPE_         VARCHAR(255) NOT NULL,
  NAME_         VARCHAR(255) NOT NULL,
  EXECUTION_ID_ VARCHAR(64),
  PROC_INST_ID_ VARCHAR(64),
  TASK_ID_      VARCHAR(64),
  BYTEARRAY_ID_ VARCHAR(64),
  DOUBLE_       DOUBLE PRECISION,
  LONG_         BIGINT,
  TEXT_         VARCHAR(4000),
  TEXT2_        VARCHAR(4000),
  PRIMARY KEY (ID_)
) IN LKMCDB03.LKMCTS10;

CREATE UNIQUE INDEX LKMC.ACT_RU_VARIABLE_ID
  ON LKMC.ACT_RU_VARIABLE (ID_);

---------------------------------

CREATE TABLESPACE LKMCTS11
IN LKMCDB03
  USING STOGROUP DB0DSG05
PRIQTY -1 SECQTY -1
BUFFERPOOL BP9;

CREATE TABLE LKMC.ACT_RU_EVENT_SUBSCR (
  ID_            VARCHAR(64)  NOT NULL,
  REV_           INTEGER,
  EVENT_TYPE_    VARCHAR(255) NOT NULL,
  EVENT_NAME_    VARCHAR(255),
  EXECUTION_ID_  VARCHAR(64),
  PROC_INST_ID_  VARCHAR(64),
  ACTIVITY_ID_   VARCHAR(64),
  CONFIGURATION_ VARCHAR(255),
  CREATED_       TIMESTAMP    NOT NULL,
  PROC_DEF_ID_   VARCHAR(64),
  TENANT_ID_     VARCHAR(255) DEFAULT '',
  PRIMARY KEY (ID_)
) IN LKMCDB03.LKMCTS11;

CREATE UNIQUE INDEX LKMC.ACT_RU_EVENT_SUBSCR_ID
  ON LKMC.ACT_RU_EVENT_SUBSCR (ID_);

---------------------------------

CREATE TABLESPACE LKMCTS12
IN LKMCDB03
  USING STOGROUP DB0DSG05
PRIQTY -1 SECQTY -1
BUFFERPOOL BP9;

CREATE TABLE LKMC.ACT_EVT_LOG (
  LOG_NR_       BIGINT    NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 1, INCREMENT BY 1),
  TYPE_         VARCHAR(64),
  PROC_DEF_ID_  VARCHAR(64),
  PROC_INST_ID_ VARCHAR(64),
  EXECUTION_ID_ VARCHAR(64),
  TASK_ID_      VARCHAR(64),
  TIME_STAMP_   TIMESTAMP NOT NULL,
  USER_ID_      VARCHAR(255),
  DATA_         BLOB,
  LOCK_OWNER_   VARCHAR(255),
  LOCK_TIME_    TIMESTAMP,
  IS_PROCESSED_ INTEGER            DEFAULT 0,
  PRIMARY KEY (LOG_NR_)
) IN LKMCDB03.LKMCTS12;

CREATE UNIQUE INDEX LKMC.ACT_EVT_LOG_LOG_NR
  ON LKMC.ACT_EVT_LOG (LOG_NR_);

---------------------------------

CREATE TABLESPACE LKMCTS13
IN LKMCDB03
  USING STOGROUP DB0DSG05
PRIQTY -1 SECQTY -1
BUFFERPOOL BP9;

CREATE TABLE LKMC.ACT_PROCDEF_INFO (
  ID_           VARCHAR(64) NOT NULL,
  PROC_DEF_ID_  VARCHAR(64) NOT NULL,
  REV_          INTEGER,
  INFO_JSON_ID_ VARCHAR(64),
  PRIMARY KEY (ID_)
) IN LKMCDB03.LKMCTS13;

CREATE UNIQUE INDEX LKMC.ACT_PROCDEF_INFO_ID
  ON LKMC.ACT_PROCDEF_INFO (ID_);

---------------------------------

CREATE INDEX LKMC.ACT_IDX_EXEC_BUSKEY
  ON LKMC.ACT_RU_EXECUTION (BUSINESS_KEY_);

CREATE INDEX LKMC.ACT_IDX_TASK_CREATE
  ON LKMC.ACT_RU_TASK (CREATE_TIME_);

CREATE INDEX LKMC.ACT_IDX_IDENT_LNK_USER
  ON LKMC.ACT_RU_IDENTITYLINK (USER_ID_);

CREATE INDEX LKMC.ACT_IDX_IDENT_LNK_GROUP
  ON LKMC.ACT_RU_IDENTITYLINK (GROUP_ID_);

CREATE INDEX LKMC.ACT_IDX_EVENT_SUBSCR_CONFIG_
  ON LKMC.ACT_RU_EVENT_SUBSCR (CONFIGURATION_);

CREATE INDEX LKMC.ACT_IDX_VARIABLE_TASK_ID
  ON LKMC.ACT_RU_VARIABLE (TASK_ID_);

CREATE INDEX LKMC.ACT_IDX_ATHRZ_PROCEDEF
  ON LKMC.ACT_RU_IDENTITYLINK (PROC_DEF_ID_);

CREATE INDEX LKMC.ACT_IDX_EXECUTION_PROC
  ON LKMC.ACT_RU_EXECUTION (PROC_DEF_ID_);

CREATE INDEX LKMC.ACT_IDX_EXECUTION_PARENT
  ON LKMC.ACT_RU_EXECUTION (PARENT_ID_);

CREATE INDEX LKMC.ACT_IDX_EXECUTION_SUPER
  ON LKMC.ACT_RU_EXECUTION (SUPER_EXEC_);

CREATE INDEX LKMC.ACT_IDX_EXECUTION_IDANDREV
  ON LKMC.ACT_RU_EXECUTION (ID_, REV_);

CREATE INDEX LKMC.ACT_IDX_VARIABLE_BA
  ON LKMC.ACT_RU_VARIABLE (BYTEARRAY_ID_);

CREATE INDEX LKMC.ACT_IDX_VARIABLE_EXEC
  ON LKMC.ACT_RU_VARIABLE (EXECUTION_ID_);

CREATE INDEX LKMC.ACT_IDX_VARIABLE_PROCINST
  ON LKMC.ACT_RU_VARIABLE (PROC_INST_ID_);

CREATE INDEX LKMC.ACT_IDX_IDENT_LNK_TASK
  ON LKMC.ACT_RU_IDENTITYLINK (TASK_ID_);

CREATE INDEX LKMC.ACT_IDX_IDENT_LNK_PROCINST
  ON LKMC.ACT_RU_IDENTITYLINK (PROC_INST_ID_);

CREATE INDEX LKMC.ACT_IDX_TASK_EXEC
  ON LKMC.ACT_RU_TASK (EXECUTION_ID_);

CREATE INDEX LKMC.ACT_IDX_TASK_PROCINST
  ON LKMC.ACT_RU_TASK (PROC_INST_ID_);

CREATE INDEX LKMC.ACT_IDX_EXEC_PROC_INST_ID
  ON LKMC.ACT_RU_EXECUTION (PROC_INST_ID_);

CREATE INDEX LKMC.ACT_IDX_TASK_PROC_DEF_ID
  ON LKMC.ACT_RU_TASK (PROC_DEF_ID_);

CREATE INDEX LKMC.ACT_IDX_EVENT_SUBSCR_EXEC_ID
  ON LKMC.ACT_RU_EVENT_SUBSCR (EXECUTION_ID_);

CREATE INDEX LKMC.ACT_IDX_JOB_EXCEPTION_STACK_ID
  ON LKMC.ACT_RU_JOB (EXCEPTION_STACK_ID_);

CREATE INDEX LKMC.ACT_IDX_INFO_PROCDEF
  ON LKMC.ACT_PROCDEF_INFO (PROC_DEF_ID_);

ALTER TABLE LKMC.ACT_GE_BYTEARRAY
  ADD CONSTRAINT ACT_FK_BYTEARR_DEPL
FOREIGN KEY (DEPLOYMENT_ID_)
REFERENCES LKMC.ACT_RE_DEPLOYMENT (ID_);

-- don't work
--ALTER TABLE LKMC.ACT_RE_PROCDEF
--  ADD CONSTRAINT ACT_UNIQ_PROCDEF
--UNIQUE (KEY_, VERSION_, TENANT_ID_);

ALTER TABLE LKMC.ACT_RU_EXECUTION
  ADD CONSTRAINT ACT_FK_EXE_PROCINST
FOREIGN KEY (PROC_INST_ID_)
REFERENCES LKMC.ACT_RU_EXECUTION (ID_) ON DELETE CASCADE;

ALTER TABLE LKMC.ACT_RU_EXECUTION
  ADD CONSTRAINT ACT_FK_EXE_PARENT
FOREIGN KEY (PARENT_ID_)
REFERENCES LKMC.ACT_RU_EXECUTION (ID_) ON DELETE CASCADE;

ALTER TABLE LKMC.ACT_RU_EXECUTION
  ADD CONSTRAINT ACT_FK_EXE_SUPER
FOREIGN KEY (SUPER_EXEC_)
REFERENCES LKMC.ACT_RU_EXECUTION (ID_) ON DELETE CASCADE;

ALTER TABLE LKMC.ACT_RU_EXECUTION
  ADD CONSTRAINT ACT_FK_EXE_PROCDEF
FOREIGN KEY (PROC_DEF_ID_)
REFERENCES LKMC.ACT_RE_PROCDEF (ID_);

ALTER TABLE LKMC.ACT_RU_IDENTITYLINK
  ADD CONSTRAINT ACT_FK_TSKASS_TASK
FOREIGN KEY (TASK_ID_)
REFERENCES LKMC.ACT_RU_TASK (ID_);

ALTER TABLE LKMC.ACT_RU_IDENTITYLINK
  ADD CONSTRAINT ACT_FK_ATHRZ_PROCEDEF
FOREIGN KEY (PROC_DEF_ID_)
REFERENCES LKMC.ACT_RE_PROCDEF (ID_);

ALTER TABLE LKMC.ACT_RU_IDENTITYLINK
  ADD CONSTRAINT ACT_FK_IDL_PROCINST
FOREIGN KEY (PROC_INST_ID_)
REFERENCES LKMC.ACT_RU_EXECUTION (ID_);

ALTER TABLE LKMC.ACT_RU_TASK
  ADD CONSTRAINT ACT_FK_TASK_EXE
FOREIGN KEY (EXECUTION_ID_)
REFERENCES LKMC.ACT_RU_EXECUTION (ID_);

ALTER TABLE LKMC.ACT_RU_TASK
  ADD CONSTRAINT ACT_FK_TASK_PROCINST
FOREIGN KEY (PROC_INST_ID_)
REFERENCES LKMC.ACT_RU_EXECUTION (ID_);

ALTER TABLE LKMC.ACT_RU_TASK
  ADD CONSTRAINT ACT_FK_TASK_PROCDEF
FOREIGN KEY (PROC_DEF_ID_)
REFERENCES LKMC.ACT_RE_PROCDEF (ID_);

ALTER TABLE LKMC.ACT_RU_VARIABLE
  ADD CONSTRAINT ACT_FK_VAR_EXE
FOREIGN KEY (EXECUTION_ID_)
REFERENCES LKMC.ACT_RU_EXECUTION (ID_);

ALTER TABLE LKMC.ACT_RU_VARIABLE
  ADD CONSTRAINT ACT_FK_VAR_PROCINST
FOREIGN KEY (PROC_INST_ID_)
REFERENCES LKMC.ACT_RU_EXECUTION (ID_);

ALTER TABLE LKMC.ACT_RU_VARIABLE
  ADD CONSTRAINT ACT_FK_VAR_BYTEARRAY
FOREIGN KEY (BYTEARRAY_ID_)
REFERENCES LKMC.ACT_GE_BYTEARRAY (ID_);

ALTER TABLE LKMC.ACT_RU_JOB
  ADD CONSTRAINT ACT_FK_JOB_EXCEPTION
FOREIGN KEY (EXCEPTION_STACK_ID_)
REFERENCES LKMC.ACT_GE_BYTEARRAY (ID_);

ALTER TABLE LKMC.ACT_RU_EVENT_SUBSCR
  ADD CONSTRAINT ACT_FK_EVENT_EXEC
FOREIGN KEY (EXECUTION_ID_)
REFERENCES LKMC.ACT_RU_EXECUTION (ID_);

ALTER TABLE LKMC.ACT_RE_MODEL
  ADD CONSTRAINT ACT_FK_MODEL_SOURCE
FOREIGN KEY (EDITOR_SOURCE_VALUE_ID_)
REFERENCES LKMC.ACT_GE_BYTEARRAY (ID_);

ALTER TABLE LKMC.ACT_RE_MODEL
  ADD CONSTRAINT ACT_FK_MODEL_SOURCE_EXTRA
FOREIGN KEY (EDITOR_SOURCE_EXTRA_VALUE_ID_)
REFERENCES LKMC.ACT_GE_BYTEARRAY (ID_);

ALTER TABLE LKMC.ACT_RE_MODEL
  ADD CONSTRAINT ACT_FK_MODEL_DEPLOYMENT
FOREIGN KEY (DEPLOYMENT_ID_)
REFERENCES LKMC.ACT_RE_DEPLOYMENT (ID_);

ALTER TABLE LKMC.ACT_PROCDEF_INFO
  ADD CONSTRAINT ACT_FK_INFO_JSON_BA
FOREIGN KEY (INFO_JSON_ID_)
REFERENCES LKMC.ACT_GE_BYTEARRAY (ID_);

ALTER TABLE LKMC.ACT_PROCDEF_INFO
  ADD CONSTRAINT ACT_FK_INFO_PROCDEF
FOREIGN KEY (PROC_DEF_ID_)
REFERENCES LKMC.ACT_RE_PROCDEF (ID_);

--don't work
--ALTER TABLE LKMC.ACT_PROCDEF_INFO
--  ADD CONSTRAINT ACT_UNIQ_INFO_PROCDEF
--UNIQUE (PROC_DEF_ID_);

-- ////////////////////////////////////
-- ////////// history /////////////////
-- ////////////////////////////////////

CREATE TABLESPACE LKMCTS14
IN LKMCDB03
  USING STOGROUP DB0DSG05
PRIQTY -1 SECQTY -1
BUFFERPOOL BP8K1;

CREATE TABLE LKMC.ACT_HI_PROCINST (
  ID_                        VARCHAR(64) NOT NULL,
  PROC_INST_ID_              VARCHAR(64) NOT NULL,
  BUSINESS_KEY_              VARCHAR(255),
  PROC_DEF_ID_               VARCHAR(64) NOT NULL,
  START_TIME_                TIMESTAMP   NOT NULL,
  END_TIME_                  TIMESTAMP,
  DURATION_                  BIGINT,
  START_USER_ID_             VARCHAR(255),
  START_ACT_ID_              VARCHAR(255),
  END_ACT_ID_                VARCHAR(255),
  SUPER_PROCESS_INSTANCE_ID_ VARCHAR(64),
  DELETE_REASON_             VARCHAR(4000),
  TENANT_ID_                 VARCHAR(255) DEFAULT '',
  NAME_                      VARCHAR(255),
  PRIMARY KEY (ID_)
) IN LKMCDB03.LKMCTS14;

CREATE UNIQUE INDEX LKMC.ACT_HI_PROCINST_ID
  ON LKMC.ACT_HI_PROCINST (ID_);

--don't work
--ALTER TABLE LKMC.ACT_HI_PROCINST
--  ADD CONSTRAINT PROC_INST_ID_ UNIQUE (PROC_INST_ID_);

---------------------------------

CREATE TABLESPACE LKMCTS15
IN LKMCDB03
  USING STOGROUP DB0DSG05
PRIQTY -1 SECQTY -1
BUFFERPOOL BP9;

CREATE TABLE LKMC.ACT_HI_ACTINST (
  ID_                VARCHAR(64)  NOT NULL,
  PROC_DEF_ID_       VARCHAR(64)  NOT NULL,
  PROC_INST_ID_      VARCHAR(64)  NOT NULL,
  EXECUTION_ID_      VARCHAR(64)  NOT NULL,
  ACT_ID_            VARCHAR(255) NOT NULL,
  TASK_ID_           VARCHAR(64),
  CALL_PROC_INST_ID_ VARCHAR(64),
  ACT_NAME_          VARCHAR(255),
  ACT_TYPE_          VARCHAR(255) NOT NULL,
  OWNER_             VARCHAR(64),
  ASSIGNEE_          VARCHAR(255),
  START_TIME_        TIMESTAMP    NOT NULL,
  END_TIME_          TIMESTAMP,
  DURATION_          BIGINT,
  TENANT_ID_         VARCHAR(255) DEFAULT '',
  PRIMARY KEY (ID_)
) IN LKMCDB03.LKMCTS15;

CREATE UNIQUE INDEX LKMC.ACT_HI_ACTINST_ID
  ON LKMC.ACT_HI_ACTINST (ID_);

---------------------------------

CREATE TABLESPACE LKMCTS16
IN LKMCDB03
  USING STOGROUP DB0DSG05
PRIQTY -1 SECQTY -1
BUFFERPOOL BP32K2;

CREATE TABLE LKMC.ACT_HI_TASKINST (
  ID_             VARCHAR(64) NOT NULL,
  PROC_DEF_ID_    VARCHAR(64),
  TASK_DEF_KEY_   VARCHAR(255),
  PROC_INST_ID_   VARCHAR(64),
  EXECUTION_ID_   VARCHAR(64),
  NAME_           VARCHAR(255),
  PARENT_TASK_ID_ VARCHAR(64),
  DESCRIPTION_    VARCHAR(4000),
  OWNER_          VARCHAR(255),
  ASSIGNEE_       VARCHAR(255),
  START_TIME_     TIMESTAMP   NOT NULL,
  CLAIM_TIME_     TIMESTAMP,
  END_TIME_       TIMESTAMP,
  DURATION_       BIGINT,
  DELETE_REASON_  VARCHAR(4000),
  PRIORITY_       INTEGER,
  DUE_DATE_       TIMESTAMP,
  FORM_KEY_       VARCHAR(255),
  CATEGORY_       VARCHAR(255),
  TENANT_ID_      VARCHAR(255) DEFAULT '',
  PRIMARY KEY (ID_)
) IN LKMCDB03.LKMCTS16;

CREATE UNIQUE INDEX LKMC.ACT_HI_TASKINST_ID
  ON LKMC.ACT_HI_TASKINST (ID_);

---------------------------------

CREATE TABLESPACE LKMCTS17
IN LKMCDB03
  USING STOGROUP DB0DSG05
PRIQTY -1 SECQTY -1 BUFFERPOOL BP32K2;

CREATE TABLE LKMC.ACT_HI_VARINST (
  ID_                VARCHAR(64)  NOT NULL,
  PROC_INST_ID_      VARCHAR(64),
  EXECUTION_ID_      VARCHAR(64),
  TASK_ID_           VARCHAR(64),
  NAME_              VARCHAR(255) NOT NULL,
  VAR_TYPE_          VARCHAR(100),
  REV_               INTEGER,
  BYTEARRAY_ID_      VARCHAR(64),
  DOUBLE_            DOUBLE PRECISION,
  LONG_              BIGINT,
  TEXT_              VARCHAR(4000),
  TEXT2_             VARCHAR(4000),
  CREATE_TIME_       TIMESTAMP,
  LAST_UPDATED_TIME_ TIMESTAMP,
  PRIMARY KEY (ID_)
) IN LKMCDB03.LKMCTS17;

CREATE UNIQUE INDEX LKMC.ACT_HI_VARINST_ID
  ON LKMC.ACT_HI_VARINST (ID_);

---------------------------------

CREATE TABLESPACE LKMCTS18
IN LKMCDB03
  USING STOGROUP DB0DSG05
PRIQTY -1 SECQTY -1 BUFFERPOOL BP32K2;

CREATE TABLE LKMC.ACT_HI_DETAIL (
  ID_           VARCHAR(64)  NOT NULL,
  TYPE_         VARCHAR(255) NOT NULL,
  PROC_INST_ID_ VARCHAR(64),
  EXECUTION_ID_ VARCHAR(64),
  TASK_ID_      VARCHAR(64),
  ACT_INST_ID_  VARCHAR(64),
  NAME_         VARCHAR(255) NOT NULL,
  VAR_TYPE_     VARCHAR(255),
  REV_          INTEGER,
  TIME_         TIMESTAMP    NOT NULL,
  BYTEARRAY_ID_ VARCHAR(64),
  DOUBLE_       DOUBLE PRECISION,
  LONG_         BIGINT,
  TEXT_         VARCHAR(4000),
  TEXT2_        VARCHAR(4000),
  PRIMARY KEY (ID_)
) IN LKMCDB03.LKMCTS18;

CREATE UNIQUE INDEX LKMC.ACT_HI_DETAIL_ID
  ON LKMC.ACT_HI_DETAIL (ID_);

---------------------------------

CREATE TABLESPACE LKMCTS19
IN LKMCDB03
  USING STOGROUP DB0DSG05
PRIQTY -1 SECQTY -1 BUFFERPOOL BP8K1;

CREATE TABLE LKMC.ACT_HI_COMMENT (
  ID_           VARCHAR(64) NOT NULL,
  TYPE_         VARCHAR(255),
  TIME_         TIMESTAMP   NOT NULL,
  USER_ID_      VARCHAR(255),
  TASK_ID_      VARCHAR(64),
  PROC_INST_ID_ VARCHAR(64),
  ACTION_       VARCHAR(255),
  MESSAGE_      VARCHAR(4000),
  FULL_MSG_     BLOB,
  PRIMARY KEY (ID_)
) IN LKMCDB03.LKMCTS19;

CREATE UNIQUE INDEX LKMC.ACT_HI_COMMENT_ID
  ON LKMC.ACT_HI_COMMENT (ID_);

---------------------------------

CREATE TABLESPACE LKMCTS20
IN LKMCDB03
  USING STOGROUP DB0DSG05
PRIQTY -1 SECQTY -1 BUFFERPOOL BP32K2;

CREATE TABLE LKMC.ACT_HI_ATTACHMENT (
  ID_           VARCHAR(64) NOT NULL,
  REV_          INTEGER,
  USER_ID_      VARCHAR(255),
  NAME_         VARCHAR(255),
  DESCRIPTION_  VARCHAR(4000),
  TYPE_         VARCHAR(255),
  TASK_ID_      VARCHAR(64),
  PROC_INST_ID_ VARCHAR(64),
  URL_          VARCHAR(4000),
  CONTENT_ID_   VARCHAR(64),
  TIME_         TIMESTAMP,
  PRIMARY KEY (ID_)
) IN LKMCDB03.LKMCTS20;

CREATE UNIQUE INDEX LKMC.ACT_HI_ATTACHMENT_ID
  ON LKMC.ACT_HI_ATTACHMENT (ID_);

---------------------------------

CREATE TABLESPACE LKMCTS21
IN LKMCDB03
  USING STOGROUP DB0DSG05
PRIQTY -1 SECQTY -1 BUFFERPOOL BP9;

CREATE TABLE LKMC.ACT_HI_IDENTITYLINK (
  ID_           VARCHAR(64) NOT NULL,
  GROUP_ID_     VARCHAR(255),
  TYPE_         VARCHAR(255),
  USER_ID_      VARCHAR(255),
  TASK_ID_      VARCHAR(64),
  PROC_INST_ID_ VARCHAR(64),
  PRIMARY KEY (ID_)
) IN LKMCDB03.LKMCTS21;

CREATE UNIQUE INDEX LKMC.ACT_HI_IDENTITYLINK_ID
  ON LKMC.ACT_HI_IDENTITYLINK (ID_);

---------------------------------

CREATE INDEX LKMC.ACT_IDX_HI_PRO_INST_END
  ON LKMC.ACT_HI_PROCINST (END_TIME_);

CREATE INDEX LKMC.ACT_IDX_HI_PRO_I_BUSKEY
  ON LKMC.ACT_HI_PROCINST (BUSINESS_KEY_);

CREATE INDEX LKMC.ACT_IDX_HI_ACT_INST_START
  ON LKMC.ACT_HI_ACTINST (START_TIME_);

CREATE INDEX LKMC.ACT_IDX_HI_ACT_INST_END
  ON LKMC.ACT_HI_ACTINST (END_TIME_);

CREATE INDEX LKMC.ACT_IDX_HI_DETAIL_PROC_INST
  ON LKMC.ACT_HI_DETAIL (PROC_INST_ID_);

CREATE INDEX LKMC.ACT_IDX_HI_DETAIL_ACT_INST
  ON LKMC.ACT_HI_DETAIL (ACT_INST_ID_);

CREATE INDEX LKMC.ACT_IDX_HI_DETAIL_TIME
  ON LKMC.ACT_HI_DETAIL (TIME_);

CREATE INDEX LKMC.ACT_IDX_HI_DETAIL_NAME
  ON LKMC.ACT_HI_DETAIL (NAME_);

CREATE INDEX LKMC.ACT_IDX_HI_DETAIL_TASK_ID
  ON LKMC.ACT_HI_DETAIL (TASK_ID_);

CREATE INDEX LKMC.ACT_IDX_HI_PROCVAR_PROC_INST
  ON LKMC.ACT_HI_VARINST (PROC_INST_ID_);

CREATE INDEX LKMC.ACT_IDX_HI_PROCVAR_NAME_TYPE
  ON LKMC.ACT_HI_VARINST (NAME_, VAR_TYPE_);

CREATE INDEX LKMC.ACT_IDX_HI_PROCVAR_TASK_ID
  ON LKMC.ACT_HI_VARINST (TASK_ID_);

CREATE INDEX LKMC.ACT_IDX_HI_ACT_INST_PROCINST
  ON LKMC.ACT_HI_ACTINST (PROC_INST_ID_, ACT_ID_);

CREATE INDEX LKMC.ACT_IDX_HI_ACT_INST_EXEC
  ON LKMC.ACT_HI_ACTINST (EXECUTION_ID_, ACT_ID_);

CREATE INDEX LKMC.ACT_IDX_HI_IDENT_LNK_USER
  ON LKMC.ACT_HI_IDENTITYLINK (USER_ID_);

CREATE INDEX LKMC.ACT_IDX_HI_IDENT_LNK_TASK
  ON LKMC.ACT_HI_IDENTITYLINK (TASK_ID_);

CREATE INDEX LKMC.ACT_IDX_HI_IDENT_LNK_PROCINST
  ON LKMC.ACT_HI_IDENTITYLINK (PROC_INST_ID_);

CREATE INDEX LKMC.ACT_IDX_HI_TASK_INST_PROCINST
  ON LKMC.ACT_HI_TASKINST (PROC_INST_ID_);

-- ////////////////////////////////////
-- ////////// identity /////////////////
-- ////////////////////////////////////

CREATE TABLESPACE LKMCTS22
IN LKMCDB03
  USING STOGROUP DB0DSG05
PRIQTY -1 SECQTY -1 BUFFERPOOL BP9;

CREATE TABLE LKMC.ACT_ID_GROUP (
  ID_   VARCHAR(64) NOT NULL,
  REV_  INTEGER,
  NAME_ VARCHAR(255),
  TYPE_ VARCHAR(255),
  PRIMARY KEY (ID_)
) IN LKMCDB03.LKMCTS22;

CREATE UNIQUE INDEX LKMC.ACT_ID_GROUP_ID
  ON LKMC.ACT_ID_GROUP (ID_);

---------------------------------

CREATE TABLESPACE LKMCTS23
IN LKMCDB03
  USING STOGROUP DB0DSG05
PRIQTY -1 SECQTY -1 BUFFERPOOL BP9;

CREATE TABLE LKMC.ACT_ID_MEMBERSHIP (
  USER_ID_  VARCHAR(64) NOT NULL,
  GROUP_ID_ VARCHAR(64) NOT NULL,
  PRIMARY KEY (USER_ID_, GROUP_ID_)
) IN LKMCDB03.LKMCTS23;

CREATE UNIQUE INDEX LKMC.ACT_ID_MEMBERSHIP_ID
  ON LKMC.ACT_ID_MEMBERSHIP (USER_ID_, GROUP_ID_);

---------------------------------

CREATE TABLESPACE LKMCTS24
IN LKMCDB03
  USING STOGROUP DB0DSG05
PRIQTY -1 SECQTY -1 BUFFERPOOL BP9;

CREATE TABLE LKMC.ACT_ID_USER (
  ID_         VARCHAR(64) NOT NULL,
  REV_        INTEGER,
  FIRST_      VARCHAR(255),
  LAST_       VARCHAR(255),
  EMAIL_      VARCHAR(255),
  PWD_        VARCHAR(255),
  PICTURE_ID_ VARCHAR(64),
  PRIMARY KEY (ID_)
) IN LKMCDB03.LKMCTS24;

CREATE UNIQUE INDEX LKMC.ACT_ID_USER_ID
  ON LKMC.ACT_ID_USER (ID_);

---------------------------------

CREATE TABLESPACE LKMCTS25
IN LKMCDB03
  USING STOGROUP DB0DSG05
PRIQTY -1 SECQTY -1 BUFFERPOOL BP9;

CREATE TABLE LKMC.ACT_ID_INFO (
  ID_        VARCHAR(64) NOT NULL,
  REV_       INTEGER,
  USER_ID_   VARCHAR(64),
  TYPE_      VARCHAR(64),
  KEY_       VARCHAR(255),
  VALUE_     VARCHAR(255),
  PASSWORD_  BLOB,
  PARENT_ID_ VARCHAR(255),
  PRIMARY KEY (ID_)
) IN LKMCDB03.LKMCTS25;

CREATE UNIQUE INDEX LKMC.ACT_ID_INFO_ID
  ON LKMC.ACT_ID_INFO (ID_);

ALTER TABLE LKMC.ACT_ID_MEMBERSHIP
  ADD CONSTRAINT ACT_FK_MEMB_GROUP
FOREIGN KEY (GROUP_ID_)
REFERENCES LKMC.ACT_ID_GROUP (ID_);

ALTER TABLE LKMC.ACT_ID_MEMBERSHIP
  ADD CONSTRAINT ACT_FK_MEMB_USER
FOREIGN KEY (USER_ID_)
REFERENCES LKMC.ACT_ID_USER (ID_);

-- ////////////////////////////////////
-- ////////// DB2 /////////////////
-- ////////////////////////////////////

CREATE TABLESPACE LKMCTS26
IN LKMCDB03
  USING STOGROUP DB0DSG05
PRIQTY 118000 SECQTY 11800
BUFFERPOOL BP9;

CREATE TABLE LKMC.PRP_AKT (
  NCONT     CHAR(11)       NOT NULL,
  DAT_OP    TIMESTAMP      NOT NULL WITH DEFAULT '0001-01-01-00.00.00.000000',
  DAT_SOOB  TIMESTAMP      NOT NULL WITH DEFAULT '0001-01-01-00.00.00.000000',
  TIP       SMALLINT       NOT NULL WITH DEFAULT,
  TIPR      SMALLINT       NOT NULL WITH DEFAULT,
  GOS_SOB   SMALLINT       NOT NULL WITH DEFAULT,
  PR_KACH   INTEGER        NOT NULL WITH DEFAULT,
  PR_ABD    SMALLINT       NOT NULL WITH DEFAULT,
  KOD_SOOB  CHAR(4)        NOT NULL,
  NAMEF     CHAR(8)        NOT NULL,
  DOR_PER   SMALLINT       NOT NULL WITH DEFAULT,
  KOD_OP    SMALLINT       NOT NULL WITH DEFAULT,
  ST_OP     INTEGER        NOT NULL WITH DEFAULT,
  ST_OTPR   INTEGER        NOT NULL WITH DEFAULT,
  DOR_OTPR  SMALLINT       NOT NULL WITH DEFAULT,
  GOS_OTPR  SMALLINT       NOT NULL WITH DEFAULT,
  ST_NAZ    INTEGER        NOT NULL WITH DEFAULT,
  DOR_NAZ   SMALLINT       NOT NULL WITH DEFAULT,
  GOS_NAZ   SMALLINT       NOT NULL WITH DEFAULT,
  NOM_N     CHAR(8)        NOT NULL,
  PR_GR     SMALLINT       NOT NULL WITH DEFAULT,
  KGR_TAR   INTEGER        NOT NULL WITH DEFAULT,
  KGR_GARM  INTEGER        NOT NULL WITH DEFAULT,
  VES_GR    INTEGER        NOT NULL WITH DEFAULT,
  DOR_SD    SMALLINT       NOT NULL WITH DEFAULT,
  DOR_PR    SMALLINT       NOT NULL WITH DEFAULT,
  GOS_SD    SMALLINT       NOT NULL WITH DEFAULT,
  GOS_PR    SMALLINT       NOT NULL WITH DEFAULT,
  IND_P     DECIMAL(13, 0) NOT NULL WITH DEFAULT,
  NOM_P     SMALLINT       NOT NULL WITH DEFAULT,
  NINV      INTEGER        NOT NULL WITH DEFAULT,
  PR_NEPR   SMALLINT       NOT NULL WITH DEFAULT,
  KOD_ZAV   SMALLINT       NOT NULL WITH DEFAULT,
  DAT_ZAV   TIMESTAMP      NOT NULL WITH DEFAULT '0001-01-01-00.00.00.000000',
  ST_ZAV    INTEGER        NOT NULL WITH DEFAULT,
  DOR_ZAV   SMALLINT       NOT NULL WITH DEFAULT,
  KOD_UCH   SMALLINT       NOT NULL WITH DEFAULT,
  DAT_UCH   TIMESTAMP      NOT NULL WITH DEFAULT '0001-01-01-00.00.00.000000',
  ST_UCH    INTEGER        NOT NULL WITH DEFAULT,
  DOR_UCH   SMALLINT       NOT NULL WITH DEFAULT,
  KOD_SOOBP CHAR(4)        NOT NULL
) IN LKMCDB03.LKMCTS26;

CREATE INDEX LKMC.AKT_DAT_OP_IN1
  ON LKMC.PRP_AKT
  (DAT_OP ASC);

CREATE INDEX LKMC.AKT_GOS_PR_IN1
  ON LKMC.PRP_AKT
  (GOS_PR ASC);

CREATE INDEX LKMC.AKT_GOS_SD_IN1
  ON LKMC.PRP_AKT
  (GOS_SD ASC);

CREATE INDEX LKMC.AKT_NCONT_IN1
  ON LKMC.PRP_AKT
  (NCONT ASC);

---------------------------------

CREATE TABLESPACE LKMCTS27
IN LKMCDB03
  USING STOGROUP DB0DSG05
PRIQTY 118000 SECQTY 11800
BUFFERPOOL BP9;

CREATE TABLE LKMC.PRP_MAIN (
  ID                  INTEGER  NOT NULL GENERATED ALWAYS AS IDENTITY (
                                        START WITH 1
                                        INCREMENT BY 1
                                        MINVALUE 1
                                        MAXVALUE 2147483647
                                        NO CYCLE
                                        CACHE 20
                                        NO ORDER ),
  NCONT               CHAR(11) NOT NULL,
  ABD_PK_PRIZ         CHAR(1)  NOT NULL,
  CODE_ADM_SOB        CHAR(2)  NOT NULL,
  CODE_STATION        CHAR(5)  NOT NULL,
  DATE                CHAR(12) NOT NULL,
  TRAIN_INDEX         CHAR(13) NOT NULL,
  NINV                CHAR(8)  NOT NULL,
  MESSAGE_CODE        CHAR(4)  NOT NULL,
  OPER_CODE           CHAR(2)  NOT NULL,
  RECEPTION_PRIZ      CHAR(1)  NOT NULL,
  DELIVERY_ROAD_CODE  CHAR(2)  NOT NULL,
  RECEPTION_ROAD_CODE CHAR(2)  NOT NULL,
  CENSUS_PLACES_CODE  CHAR(1)  NOT NULL,
  CENSUS_TYPE_CODE    CHAR(1)  NOT NULL,
  PARK_NUMBER         CHAR(2)  NOT NULL,
  PATH_NUMBER         CHAR(2)  NOT NULL,
  TYPE_SIZE           CHAR(4)  NOT NULL,
  CONT_TYPE           CHAR(1)  NOT NULL,
  GROSS_WEIGHT        CHAR(2)  NOT NULL,
  TECHNICAL_CODE      CHAR(2)  NOT NULL,
  TRANSMISSION_DATE   CHAR(8)  NOT NULL,
  CENSUS_CUR_DATE     CHAR(4)  NOT NULL,
  PRIMARY KEY (ID)
) IN LKMCDB03.LKMCTS27;

CREATE UNIQUE INDEX LKMC.PRP_MAIN_ID
  ON LKMC.PRP_MAIN (ID);

---------------------------------

CREATE TABLESPACE LKMCTS28
IN LKMCDB03
  USING STOGROUP DB0DSG05
PRIQTY 118000 SECQTY 11800
BUFFERPOOL BP9;

CREATE TABLE LKMC.PRP_IBMU (
  ID                       INTEGER  NOT NULL GENERATED ALWAYS AS IDENTITY (
                                             START WITH 1
                                             INCREMENT BY 1
                                             MINVALUE 1
                                             MAXVALUE 2147483647
                                             NO CYCLE
                                             CACHE 20
                                             NO ORDER ),
  NUM                      CHAR(11) NOT NULL,
  ABD_PK_PRIZ              CHAR(1)  NOT NULL,
  CODE_ADM_SOB             CHAR(2)  NOT NULL,
  CODE_STATION             CHAR(5)  NOT NULL,
  DATE                     CHAR(12) NOT NULL,
  TRAIN_INDEX              CHAR(13) NOT NULL,
  NINV                     CHAR(8)  NOT NULL,
  MESSAGE_CODE             CHAR(4)  NOT NULL,
  OPER_CODE                CHAR(2)  NOT NULL,
  RECEPTION_PRIZ           CHAR(1)  NOT NULL,
  DELIVERY_ROAD_CODE       CHAR(2)  NOT NULL,
  RECEPTION_ROAD_CODE      CHAR(2)  NOT NULL,
  COUNTRY_CODE_DEPARTURE   CHAR(3)  NOT NULL,
  COUNTRY_CODE_DESTINATION CHAR(3)  NOT NULL,
  STATION_CODE_DEPARTURE   CHAR(5)  NOT NULL,
  STATION_CODE_DESTINATION CHAR(5)  NOT NULL,
  PPV_NUMBER               CHAR(5)  NOT NULL,
  PRIMARY KEY (ID)
) IN LKMCDB03.LKMCTS28;

CREATE UNIQUE INDEX LKMC.PRP_IBMU_ID
  ON LKMC.PRP_IBMU (ID);

---------------------------------

CREATE TABLESPACE LKMCTS29
IN LKMCDB03
  USING STOGROUP DB0DSG05
PRIQTY -1 SECQTY -1
BUFFERPOOL BP9;

CREATE TABLE LKMC.PRP_SVERKA2 (
  NCONT       CHAR(11) NOT NULL,
  REVISE_PRIZ CHAR(1)  NOT NULL
) IN LKMCDB03.LKMCTS29;


